/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.api;

import com.delphix.dct.ApiException;
import com.delphix.dct.models.MaskingFileUploadParameters;
import com.delphix.dct.models.MaskingFileUploadResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MaskingFilesApi
 */
@Ignore
public class MaskingFilesApiTest {

    private final MaskingFilesApi api = new MaskingFilesApi();

    
    /**
     * Upload a file for masking.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadMaskingFileTest() throws ApiException {
        MaskingFileUploadParameters maskingFileUploadParameters = null;
        MaskingFileUploadResponse response = api.uploadMaskingFile(maskingFileUploadParameters);

        // TODO: test validations
    }
    
}
