/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnableScaleTestingRequest
 */
public class EnableScaleTestingRequestTest {
    private final EnableScaleTestingRequest model = new EnableScaleTestingRequest();

    /**
     * Model tests for EnableScaleTestingRequest
     */
    @Test
    public void testEnableScaleTestingRequest() {
        // TODO: test EnableScaleTestingRequest
    }

    /**
     * Test the property 'enginesCount'
     */
    @Test
    public void enginesCountTest() {
        // TODO: test enginesCount
    }

    /**
     * Test the property 'virtEnginesList'
     */
    @Test
    public void virtEnginesListTest() {
        // TODO: test virtEnginesList
    }

    /**
     * Test the property 'maskingEnginesList'
     */
    @Test
    public void maskingEnginesListTest() {
        // TODO: test maskingEnginesList
    }

    /**
     * Test the property 'virtObjectsCount'
     */
    @Test
    public void virtObjectsCountTest() {
        // TODO: test virtObjectsCount
    }

    /**
     * Test the property 'snapshotsCount'
     */
    @Test
    public void snapshotsCountTest() {
        // TODO: test snapshotsCount
    }

    /**
     * Test the property 'maskingObjectsCount'
     */
    @Test
    public void maskingObjectsCountTest() {
        // TODO: test maskingObjectsCount
    }

}
