/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnginePerformanceAnalyticTrendDatapoint
 */
public class EnginePerformanceAnalyticTrendDatapointTest {
    private final EnginePerformanceAnalyticTrendDatapoint model = new EnginePerformanceAnalyticTrendDatapoint();

    /**
     * Model tests for EnginePerformanceAnalyticTrendDatapoint
     */
    @Test
    public void testEnginePerformanceAnalyticTrendDatapoint() {
        // TODO: test EnginePerformanceAnalyticTrendDatapoint
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

}
