/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HyperscaleDataTypeEnum
 */
public class HyperscaleDataTypeEnumTest {
    /**
     * Model tests for HyperscaleDataTypeEnum
     */
    @Test
    public void testHyperscaleDataTypeEnum() {
        // TODO: test HyperscaleDataTypeEnum
    }

}
