/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InstallMaskingPluginParameters
 */
public class InstallMaskingPluginParametersTest {
    private final InstallMaskingPluginParameters model = new InstallMaskingPluginParameters();

    /**
     * Model tests for InstallMaskingPluginParameters
     */
    @Test
    public void testInstallMaskingPluginParameters() {
        // TODO: test InstallMaskingPluginParameters
    }

    /**
     * Test the property 'pluginFileReference'
     */
    @Test
    public void pluginFileReferenceTest() {
        // TODO: test pluginFileReference
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
