/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Framework;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MaskingPlugin
 */
public class MaskingPluginTest {
    private final MaskingPlugin model = new MaskingPlugin();

    /**
     * Model tests for MaskingPlugin
     */
    @Test
    public void testMaskingPlugin() {
        // TODO: test MaskingPlugin
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pluginType'
     */
    @Test
    public void pluginTypeTest() {
        // TODO: test pluginType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'installDate'
     */
    @Test
    public void installDateTest() {
        // TODO: test installDate
    }

    /**
     * Test the property 'builtIn'
     */
    @Test
    public void builtInTest() {
        // TODO: test builtIn
    }

    /**
     * Test the property 'sdkVersion'
     */
    @Test
    public void sdkVersionTest() {
        // TODO: test sdkVersion
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'frameworks'
     */
    @Test
    public void frameworksTest() {
        // TODO: test frameworks
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
