/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Parameters to create a masking algorithm.
 */
@ApiModel(description = "Parameters to create a masking algorithm.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class AlgorithmCreateParameters {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PLUGIN_ID = "plugin_id";
  @SerializedName(SERIALIZED_NAME_PLUGIN_ID)
  private String pluginId;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private Map<String, Object> config = new HashMap<String, Object>();

  public static final String SERIALIZED_NAME_FRAMEWORK_NAME = "framework_name";
  @SerializedName(SERIALIZED_NAME_FRAMEWORK_NAME)
  private String frameworkName;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Tag> tags = null;


  public AlgorithmCreateParameters name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this Algorithm.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Address", required = true, value = "The name of this Algorithm.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AlgorithmCreateParameters description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description of this algorithm.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A description of this algorithm.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public AlgorithmCreateParameters pluginId(String pluginId) {
    
    this.pluginId = pluginId;
    return this;
  }

   /**
   * The id of the plugin which this algorithm will use.
   * @return pluginId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "dc91e41c-aade-4404-9084-179cb90d07c6", required = true, value = "The id of the plugin which this algorithm will use.")

  public String getPluginId() {
    return pluginId;
  }


  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }


  public AlgorithmCreateParameters config(Map<String, Object> config) {
    
    this.config = config;
    return this;
  }

  public AlgorithmCreateParameters putConfigItem(String key, Object configItem) {
    this.config.put(key, configItem);
    return this;
  }

   /**
   * The configuration of this algorithm.
   * @return config
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The configuration of this algorithm.")

  public Map<String, Object> getConfig() {
    return config;
  }


  public void setConfig(Map<String, Object> config) {
    this.config = config;
  }


  public AlgorithmCreateParameters frameworkName(String frameworkName) {
    
    this.frameworkName = frameworkName;
    return this;
  }

   /**
   * Name for the framework of this algorithm.
   * @return frameworkName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name for the framework of this algorithm.")

  public String getFrameworkName() {
    return frameworkName;
  }


  public void setFrameworkName(String frameworkName) {
    this.frameworkName = frameworkName;
  }


  public AlgorithmCreateParameters tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public AlgorithmCreateParameters addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The tags of this algorithm.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tags of this algorithm.")

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmCreateParameters algorithmCreateParameters = (AlgorithmCreateParameters) o;
    return Objects.equals(this.name, algorithmCreateParameters.name) &&
        Objects.equals(this.description, algorithmCreateParameters.description) &&
        Objects.equals(this.pluginId, algorithmCreateParameters.pluginId) &&
        Objects.equals(this.config, algorithmCreateParameters.config) &&
        Objects.equals(this.frameworkName, algorithmCreateParameters.frameworkName) &&
        Objects.equals(this.tags, algorithmCreateParameters.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, pluginId, config, frameworkName, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmCreateParameters {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    pluginId: ").append(toIndentedString(pluginId)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    frameworkName: ").append(toIndentedString(frameworkName)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

