/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Parameters to create a masking algorithm revision.
 */
@ApiModel(description = "Parameters to create a masking algorithm revision.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class AlgorithmRevisionCreateParameters {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_PLUGIN_ID = "plugin_id";
  @SerializedName(SERIALIZED_NAME_PLUGIN_ID)
  private String pluginId;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private Map<String, Object> config = new HashMap<String, Object>();

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Tag> tags = null;


  public AlgorithmRevisionCreateParameters name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this Algorithm.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Address", required = true, value = "The name of this Algorithm.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AlgorithmRevisionCreateParameters note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * A note of this algorithm.
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A note of this algorithm.")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public AlgorithmRevisionCreateParameters pluginId(String pluginId) {
    
    this.pluginId = pluginId;
    return this;
  }

   /**
   * The id of the plugin which this algorithm will use.
   * @return pluginId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "dc91e41c-aade-4404-9084-179cb90d07c6", required = true, value = "The id of the plugin which this algorithm will use.")

  public String getPluginId() {
    return pluginId;
  }


  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }


  public AlgorithmRevisionCreateParameters config(Map<String, Object> config) {
    
    this.config = config;
    return this;
  }

  public AlgorithmRevisionCreateParameters putConfigItem(String key, Object configItem) {
    this.config.put(key, configItem);
    return this;
  }

   /**
   * The configuration of this algorithm revision.
   * @return config
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The configuration of this algorithm revision.")

  public Map<String, Object> getConfig() {
    return config;
  }


  public void setConfig(Map<String, Object> config) {
    this.config = config;
  }


  public AlgorithmRevisionCreateParameters tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public AlgorithmRevisionCreateParameters addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The tags of this algorithm revision.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tags of this algorithm revision.")

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmRevisionCreateParameters algorithmRevisionCreateParameters = (AlgorithmRevisionCreateParameters) o;
    return Objects.equals(this.name, algorithmRevisionCreateParameters.name) &&
        Objects.equals(this.note, algorithmRevisionCreateParameters.note) &&
        Objects.equals(this.pluginId, algorithmRevisionCreateParameters.pluginId) &&
        Objects.equals(this.config, algorithmRevisionCreateParameters.config) &&
        Objects.equals(this.tags, algorithmRevisionCreateParameters.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, note, pluginId, config, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmRevisionCreateParameters {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    pluginId: ").append(toIndentedString(pluginId)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

