/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.AlgorithmRevisionOriginEngine;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * A masking algorithm revision.
 */
@ApiModel(description = "A masking algorithm revision.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class AlgorithmRevision {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_ALGORITHM_ID = "algorithm_id";
  @SerializedName(SERIALIZED_NAME_ALGORITHM_ID)
  private String algorithmId;

  public static final String SERIALIZED_NAME_PLUGIN_ID = "plugin_id";
  @SerializedName(SERIALIZED_NAME_PLUGIN_ID)
  private String pluginId;

  public static final String SERIALIZED_NAME_FRAMEWORK_ID = "framework_id";
  @SerializedName(SERIALIZED_NAME_FRAMEWORK_ID)
  private String frameworkId;

  public static final String SERIALIZED_NAME_IS_PRIMARY = "is_primary";
  @SerializedName(SERIALIZED_NAME_IS_PRIMARY)
  private Boolean isPrimary;

  public static final String SERIALIZED_NAME_IS_DEFAULT_INSTANCE = "is_default_instance";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT_INSTANCE)
  private Boolean isDefaultInstance;

  public static final String SERIALIZED_NAME_CREATE_DATE = "create_date";
  @SerializedName(SERIALIZED_NAME_CREATE_DATE)
  private OffsetDateTime createDate;

  public static final String SERIALIZED_NAME_ORIGIN_ENGINES = "origin_engines";
  @SerializedName(SERIALIZED_NAME_ORIGIN_ENGINES)
  private List<AlgorithmRevisionOriginEngine> originEngines = null;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private Map<String, Object> config = null;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Tag> tags = null;


  public AlgorithmRevision id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The algorithm revision ID.
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "a638d976-6b7e-43f4-9212-90f4dc6d405c", required = true, value = "The algorithm revision ID.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public AlgorithmRevision name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this algorithm revision.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Dev", required = true, value = "The name of this algorithm revision.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AlgorithmRevision note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * A note of this algorithm.
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A note of this algorithm.")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public AlgorithmRevision algorithmId(String algorithmId) {
    
    this.algorithmId = algorithmId;
    return this;
  }

   /**
   * The id of the algorithm that this revision belongs to.
   * @return algorithmId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "a638d976-6b7e-43f4-9212-90f4dc6d405c", required = true, value = "The id of the algorithm that this revision belongs to.")

  public String getAlgorithmId() {
    return algorithmId;
  }


  public void setAlgorithmId(String algorithmId) {
    this.algorithmId = algorithmId;
  }


  public AlgorithmRevision pluginId(String pluginId) {
    
    this.pluginId = pluginId;
    return this;
  }

   /**
   * The id of the plugin that this algorithm revision belongs to.
   * @return pluginId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "a638d976-6b7e-43f4-9212-90f4dc6d405c", required = true, value = "The id of the plugin that this algorithm revision belongs to.")

  public String getPluginId() {
    return pluginId;
  }


  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }


  public AlgorithmRevision frameworkId(String frameworkId) {
    
    this.frameworkId = frameworkId;
    return this;
  }

   /**
   * The id of the framework that this algorithm revision belongs to.
   * @return frameworkId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "a638d976-6b7e-43f4-9212-90f4dc6d405c", required = true, value = "The id of the framework that this algorithm revision belongs to.")

  public String getFrameworkId() {
    return frameworkId;
  }


  public void setFrameworkId(String frameworkId) {
    this.frameworkId = frameworkId;
  }


  public AlgorithmRevision isPrimary(Boolean isPrimary) {
    
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * Whether this algorithm revision is the primary revision of its algorithm.
   * @return isPrimary
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether this algorithm revision is the primary revision of its algorithm.")

  public Boolean getIsPrimary() {
    return isPrimary;
  }


  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }


  public AlgorithmRevision isDefaultInstance(Boolean isDefaultInstance) {
    
    this.isDefaultInstance = isDefaultInstance;
    return this;
  }

   /**
   * Whether this algorithm revision is defined in a plugin as a default instance.
   * @return isDefaultInstance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether this algorithm revision is defined in a plugin as a default instance.")

  public Boolean getIsDefaultInstance() {
    return isDefaultInstance;
  }


  public void setIsDefaultInstance(Boolean isDefaultInstance) {
    this.isDefaultInstance = isDefaultInstance;
  }


  public AlgorithmRevision createDate(OffsetDateTime createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * The date and time this algorithm revision was created.
   * @return createDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-11-30T08:51:34.148Z", value = "The date and time this algorithm revision was created.")

  public OffsetDateTime getCreateDate() {
    return createDate;
  }


  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public AlgorithmRevision originEngines(List<AlgorithmRevisionOriginEngine> originEngines) {
    
    this.originEngines = originEngines;
    return this;
  }

  public AlgorithmRevision addOriginEnginesItem(AlgorithmRevisionOriginEngine originEnginesItem) {
    if (this.originEngines == null) {
      this.originEngines = new ArrayList<AlgorithmRevisionOriginEngine>();
    }
    this.originEngines.add(originEnginesItem);
    return this;
  }

   /**
   * The engines that this algorithm revision is originated from.
   * @return originEngines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The engines that this algorithm revision is originated from.")

  public List<AlgorithmRevisionOriginEngine> getOriginEngines() {
    return originEngines;
  }


  public void setOriginEngines(List<AlgorithmRevisionOriginEngine> originEngines) {
    this.originEngines = originEngines;
  }


  public AlgorithmRevision config(Map<String, Object> config) {
    
    this.config = config;
    return this;
  }

  public AlgorithmRevision putConfigItem(String key, Object configItem) {
    if (this.config == null) {
      this.config = new HashMap<String, Object>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * The configuration of this algorithm revision.
   * @return config
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The configuration of this algorithm revision.")

  public Map<String, Object> getConfig() {
    return config;
  }


  public void setConfig(Map<String, Object> config) {
    this.config = config;
  }


  public AlgorithmRevision tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public AlgorithmRevision addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The tags of this algorithm revision.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tags of this algorithm revision.")

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmRevision algorithmRevision = (AlgorithmRevision) o;
    return Objects.equals(this.id, algorithmRevision.id) &&
        Objects.equals(this.name, algorithmRevision.name) &&
        Objects.equals(this.note, algorithmRevision.note) &&
        Objects.equals(this.algorithmId, algorithmRevision.algorithmId) &&
        Objects.equals(this.pluginId, algorithmRevision.pluginId) &&
        Objects.equals(this.frameworkId, algorithmRevision.frameworkId) &&
        Objects.equals(this.isPrimary, algorithmRevision.isPrimary) &&
        Objects.equals(this.isDefaultInstance, algorithmRevision.isDefaultInstance) &&
        Objects.equals(this.createDate, algorithmRevision.createDate) &&
        Objects.equals(this.originEngines, algorithmRevision.originEngines) &&
        Objects.equals(this.config, algorithmRevision.config) &&
        Objects.equals(this.tags, algorithmRevision.tags);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && a.get().getClass().isArray() ? Arrays.equals((T[])a.get(), (T[])b.get()) : Objects.equals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, note, algorithmId, pluginId, frameworkId, isPrimary, isDefaultInstance, createDate, originEngines, config, tags);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent()
      ? (a.get().getClass().isArray() ? Arrays.hashCode((T[])a.get()) : Objects.hashCode(a.get()))
      : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmRevision {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    algorithmId: ").append(toIndentedString(algorithmId)).append("\n");
    sb.append("    pluginId: ").append(toIndentedString(pluginId)).append("\n");
    sb.append("    frameworkId: ").append(toIndentedString(frameworkId)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    isDefaultInstance: ").append(toIndentedString(isDefaultInstance)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    originEngines: ").append(toIndentedString(originEngines)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

