/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A record of engine that an algorithm revision originates from.
 */
@ApiModel(description = "A record of engine that an algorithm revision originates from.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class AlgorithmRevisionOriginEngine {
  public static final String SERIALIZED_NAME_ENGINE_ID = "engine_id";
  @SerializedName(SERIALIZED_NAME_ENGINE_ID)
  private String engineId;

  public static final String SERIALIZED_NAME_ENGINE_NAME = "engine_name";
  @SerializedName(SERIALIZED_NAME_ENGINE_NAME)
  private String engineName;


  public AlgorithmRevisionOriginEngine engineId(String engineId) {
    
    this.engineId = engineId;
    return this;
  }

   /**
   * The id of the engine that this algorithm revision is originated from.
   * @return engineId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123", value = "The id of the engine that this algorithm revision is originated from.")

  public String getEngineId() {
    return engineId;
  }


  public void setEngineId(String engineId) {
    this.engineId = engineId;
  }


  public AlgorithmRevisionOriginEngine engineName(String engineName) {
    
    this.engineName = engineName;
    return this;
  }

   /**
   * The name of the engine that this algorithm revision is originated from.
   * @return engineName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "dev engine", value = "The name of the engine that this algorithm revision is originated from.")

  public String getEngineName() {
    return engineName;
  }


  public void setEngineName(String engineName) {
    this.engineName = engineName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmRevisionOriginEngine algorithmRevisionOriginEngine = (AlgorithmRevisionOriginEngine) o;
    return Objects.equals(this.engineId, algorithmRevisionOriginEngine.engineId) &&
        Objects.equals(this.engineName, algorithmRevisionOriginEngine.engineName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(engineId, engineName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmRevisionOriginEngine {\n");
    sb.append("    engineId: ").append(toIndentedString(engineId)).append("\n");
    sb.append("    engineName: ").append(toIndentedString(engineName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

