/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * A masking algorithm.
 */
@ApiModel(description = "A masking algorithm.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class Algorithm {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PLUGIN_NAME = "plugin_name";
  @SerializedName(SERIALIZED_NAME_PLUGIN_NAME)
  private String pluginName;

  public static final String SERIALIZED_NAME_FRAMEWORK_NAME = "framework_name";
  @SerializedName(SERIALIZED_NAME_FRAMEWORK_NAME)
  private String frameworkName;

  public static final String SERIALIZED_NAME_CREATE_DATE = "create_date";
  @SerializedName(SERIALIZED_NAME_CREATE_DATE)
  private OffsetDateTime createDate;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Tag> tags = null;


  public Algorithm id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The algorithm entity ID.
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "a638d976-6b7e-43f4-9212-90f4dc6d405c", required = true, value = "The algorithm entity ID.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Algorithm name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this algorithm.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Address", required = true, value = "The name of this algorithm.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Algorithm description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description of this algorithm.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A description of this algorithm.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Algorithm pluginName(String pluginName) {
    
    this.pluginName = pluginName;
    return this;
  }

   /**
   * The name of the plugin that this algorithm belongs to.
   * @return pluginName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "dlpx-core", required = true, value = "The name of the plugin that this algorithm belongs to.")

  public String getPluginName() {
    return pluginName;
  }


  public void setPluginName(String pluginName) {
    this.pluginName = pluginName;
  }


  public Algorithm frameworkName(String frameworkName) {
    
    this.frameworkName = frameworkName;
    return this;
  }

   /**
   * The name of the framework that this algorithm belongs to.
   * @return frameworkName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Secure Lookup", required = true, value = "The name of the framework that this algorithm belongs to.")

  public String getFrameworkName() {
    return frameworkName;
  }


  public void setFrameworkName(String frameworkName) {
    this.frameworkName = frameworkName;
  }


  public Algorithm createDate(OffsetDateTime createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * The date and time this algorithm was created.
   * @return createDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-11-30T08:51:34.148Z", value = "The date and time this algorithm was created.")

  public OffsetDateTime getCreateDate() {
    return createDate;
  }


  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public Algorithm tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public Algorithm addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The tags of this algorithm.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tags of this algorithm.")

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Algorithm algorithm = (Algorithm) o;
    return Objects.equals(this.id, algorithm.id) &&
        Objects.equals(this.name, algorithm.name) &&
        Objects.equals(this.description, algorithm.description) &&
        Objects.equals(this.pluginName, algorithm.pluginName) &&
        Objects.equals(this.frameworkName, algorithm.frameworkName) &&
        Objects.equals(this.createDate, algorithm.createDate) &&
        Objects.equals(this.tags, algorithm.tags);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && a.get().getClass().isArray() ? Arrays.equals((T[])a.get(), (T[])b.get()) : Objects.equals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, pluginName, frameworkName, createDate, tags);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent()
      ? (a.get().getClass().isArray() ? Arrays.hashCode((T[])a.get()) : Objects.hashCode(a.get()))
      : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Algorithm {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    pluginName: ").append(toIndentedString(pluginName)).append("\n");
    sb.append("    frameworkName: ").append(toIndentedString(frameworkName)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

