/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The global totals of different actions performed across all accounts.
 */
@ApiModel(description = "The global totals of different actions performed across all accounts.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class AuditLogsSummaryTotals {
  public static final String SERIALIZED_NAME_TOTAL_VDB_REFRESHES = "total_vdb_refreshes";
  @SerializedName(SERIALIZED_NAME_TOTAL_VDB_REFRESHES)
  private Integer totalVdbRefreshes;

  public static final String SERIALIZED_NAME_TOTAL_MASKING_JOBS = "total_masking_jobs";
  @SerializedName(SERIALIZED_NAME_TOTAL_MASKING_JOBS)
  private Integer totalMaskingJobs;


  public AuditLogsSummaryTotals totalVdbRefreshes(Integer totalVdbRefreshes) {
    
    this.totalVdbRefreshes = totalVdbRefreshes;
    return this;
  }

   /**
   * Get totalVdbRefreshes
   * @return totalVdbRefreshes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalVdbRefreshes() {
    return totalVdbRefreshes;
  }


  public void setTotalVdbRefreshes(Integer totalVdbRefreshes) {
    this.totalVdbRefreshes = totalVdbRefreshes;
  }


  public AuditLogsSummaryTotals totalMaskingJobs(Integer totalMaskingJobs) {
    
    this.totalMaskingJobs = totalMaskingJobs;
    return this;
  }

   /**
   * Get totalMaskingJobs
   * @return totalMaskingJobs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalMaskingJobs() {
    return totalMaskingJobs;
  }


  public void setTotalMaskingJobs(Integer totalMaskingJobs) {
    this.totalMaskingJobs = totalMaskingJobs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogsSummaryTotals auditLogsSummaryTotals = (AuditLogsSummaryTotals) o;
    return Objects.equals(this.totalVdbRefreshes, auditLogsSummaryTotals.totalVdbRefreshes) &&
        Objects.equals(this.totalMaskingJobs, auditLogsSummaryTotals.totalMaskingJobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalVdbRefreshes, totalMaskingJobs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogsSummaryTotals {\n");
    sb.append("    totalVdbRefreshes: ").append(toIndentedString(totalVdbRefreshes)).append("\n");
    sb.append("    totalMaskingJobs: ").append(toIndentedString(totalMaskingJobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

