/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EngineGlobalObjectStateData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class EngineGlobalObjectStateData {
  public static final String SERIALIZED_NAME_ENGINE_ID = "engine_id";
  @SerializedName(SERIALIZED_NAME_ENGINE_ID)
  private String engineId;

  public static final String SERIALIZED_NAME_ENGINE_NAME = "engine_name";
  @SerializedName(SERIALIZED_NAME_ENGINE_NAME)
  private String engineName;

  public static final String SERIALIZED_NAME_JOBS_COUNT = "jobs_count";
  @SerializedName(SERIALIZED_NAME_JOBS_COUNT)
  private Integer jobsCount;

  public static final String SERIALIZED_NAME_CONNECTORS_COUNT = "connectors_count";
  @SerializedName(SERIALIZED_NAME_CONNECTORS_COUNT)
  private Integer connectorsCount;

  public static final String SERIALIZED_NAME_RULESETS_COUNT = "rulesets_count";
  @SerializedName(SERIALIZED_NAME_RULESETS_COUNT)
  private Integer rulesetsCount;

  public static final String SERIALIZED_NAME_GLOBAL_OBJECT_REVISION_HASH = "global_object_revision_hash";
  @SerializedName(SERIALIZED_NAME_GLOBAL_OBJECT_REVISION_HASH)
  private String globalObjectRevisionHash;


  public EngineGlobalObjectStateData engineId(String engineId) {
    
    this.engineId = engineId;
    return this;
  }

   /**
   * The entity ID of the engine.
   * @return engineId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4ed2357d-f1a7-410c-b951-90f0edc1a0f6", value = "The entity ID of the engine.")

  public String getEngineId() {
    return engineId;
  }


  public void setEngineId(String engineId) {
    this.engineId = engineId;
  }


  public EngineGlobalObjectStateData engineName(String engineName) {
    
    this.engineName = engineName;
    return this;
  }

   /**
   * The name of the engine.
   * @return engineName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My favorite engine", value = "The name of the engine.")

  public String getEngineName() {
    return engineName;
  }


  public void setEngineName(String engineName) {
    this.engineName = engineName;
  }


  public EngineGlobalObjectStateData jobsCount(Integer jobsCount) {
    
    this.jobsCount = jobsCount;
    return this;
  }

   /**
   * The number of masking jobs present on the engine.
   * @return jobsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The number of masking jobs present on the engine.")

  public Integer getJobsCount() {
    return jobsCount;
  }


  public void setJobsCount(Integer jobsCount) {
    this.jobsCount = jobsCount;
  }


  public EngineGlobalObjectStateData connectorsCount(Integer connectorsCount) {
    
    this.connectorsCount = connectorsCount;
    return this;
  }

   /**
   * The number of connectors present on the engine.
   * @return connectorsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25", value = "The number of connectors present on the engine.")

  public Integer getConnectorsCount() {
    return connectorsCount;
  }


  public void setConnectorsCount(Integer connectorsCount) {
    this.connectorsCount = connectorsCount;
  }


  public EngineGlobalObjectStateData rulesetsCount(Integer rulesetsCount) {
    
    this.rulesetsCount = rulesetsCount;
    return this;
  }

   /**
   * The number of rulesets present on the engine.
   * @return rulesetsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25", value = "The number of rulesets present on the engine.")

  public Integer getRulesetsCount() {
    return rulesetsCount;
  }


  public void setRulesetsCount(Integer rulesetsCount) {
    this.rulesetsCount = rulesetsCount;
  }


  public EngineGlobalObjectStateData globalObjectRevisionHash(String globalObjectRevisionHash) {
    
    this.globalObjectRevisionHash = globalObjectRevisionHash;
    return this;
  }

   /**
   * The revisionHash of the GLOBAL_OBJECT.
   * @return globalObjectRevisionHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "dfb515e3d9727eebf499cb252b417efc926bad0b", value = "The revisionHash of the GLOBAL_OBJECT.")

  public String getGlobalObjectRevisionHash() {
    return globalObjectRevisionHash;
  }


  public void setGlobalObjectRevisionHash(String globalObjectRevisionHash) {
    this.globalObjectRevisionHash = globalObjectRevisionHash;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EngineGlobalObjectStateData engineGlobalObjectStateData = (EngineGlobalObjectStateData) o;
    return Objects.equals(this.engineId, engineGlobalObjectStateData.engineId) &&
        Objects.equals(this.engineName, engineGlobalObjectStateData.engineName) &&
        Objects.equals(this.jobsCount, engineGlobalObjectStateData.jobsCount) &&
        Objects.equals(this.connectorsCount, engineGlobalObjectStateData.connectorsCount) &&
        Objects.equals(this.rulesetsCount, engineGlobalObjectStateData.rulesetsCount) &&
        Objects.equals(this.globalObjectRevisionHash, engineGlobalObjectStateData.globalObjectRevisionHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(engineId, engineName, jobsCount, connectorsCount, rulesetsCount, globalObjectRevisionHash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EngineGlobalObjectStateData {\n");
    sb.append("    engineId: ").append(toIndentedString(engineId)).append("\n");
    sb.append("    engineName: ").append(toIndentedString(engineName)).append("\n");
    sb.append("    jobsCount: ").append(toIndentedString(jobsCount)).append("\n");
    sb.append("    connectorsCount: ").append(toIndentedString(connectorsCount)).append("\n");
    sb.append("    rulesetsCount: ").append(toIndentedString(rulesetsCount)).append("\n");
    sb.append("    globalObjectRevisionHash: ").append(toIndentedString(globalObjectRevisionHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

