/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Global properties response.
 */
@ApiModel(description = "Global properties response.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class GlobalProperties {
  public static final String SERIALIZED_NAME_DISABLE_USERNAME_PASSWORD = "disable_username_password";
  @SerializedName(SERIALIZED_NAME_DISABLE_USERNAME_PASSWORD)
  private Boolean disableUsernamePassword;

  public static final String SERIALIZED_NAME_PHONEHOME_UPLOAD_CADENCE = "phonehome_upload_cadence";
  @SerializedName(SERIALIZED_NAME_PHONEHOME_UPLOAD_CADENCE)
  private Integer phonehomeUploadCadence;

  public static final String SERIALIZED_NAME_PHONEHOME_MAXIMUM_TRANSFER_SIZE = "phonehome_maximum_transfer_size";
  @SerializedName(SERIALIZED_NAME_PHONEHOME_MAXIMUM_TRANSFER_SIZE)
  private Integer phonehomeMaximumTransferSize;


  public GlobalProperties disableUsernamePassword(Boolean disableUsernamePassword) {
    
    this.disableUsernamePassword = disableUsernamePassword;
    return this;
  }

   /**
   * Property to define either username &amp; password based authentication disabled or not.
   * @return disableUsernamePassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Property to define either username & password based authentication disabled or not.")

  public Boolean getDisableUsernamePassword() {
    return disableUsernamePassword;
  }


  public void setDisableUsernamePassword(Boolean disableUsernamePassword) {
    this.disableUsernamePassword = disableUsernamePassword;
  }


  public GlobalProperties phonehomeUploadCadence(Integer phonehomeUploadCadence) {
    
    this.phonehomeUploadCadence = phonehomeUploadCadence;
    return this;
  }

   /**
   * Property to define the phonehome bundle upload cadence, in days, if Delphix services are reachable.
   * minimum: 1
   * maximum: 30
   * @return phonehomeUploadCadence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Property to define the phonehome bundle upload cadence, in days, if Delphix services are reachable.")

  public Integer getPhonehomeUploadCadence() {
    return phonehomeUploadCadence;
  }


  public void setPhonehomeUploadCadence(Integer phonehomeUploadCadence) {
    this.phonehomeUploadCadence = phonehomeUploadCadence;
  }


  public GlobalProperties phonehomeMaximumTransferSize(Integer phonehomeMaximumTransferSize) {
    
    this.phonehomeMaximumTransferSize = phonehomeMaximumTransferSize;
    return this;
  }

   /**
   * Property to define the maximum uncompressed bundle transfer size, in bytes, for phonehome.
   * minimum: 1048576
   * maximum: 1073741824
   * @return phonehomeMaximumTransferSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Property to define the maximum uncompressed bundle transfer size, in bytes, for phonehome.")

  public Integer getPhonehomeMaximumTransferSize() {
    return phonehomeMaximumTransferSize;
  }


  public void setPhonehomeMaximumTransferSize(Integer phonehomeMaximumTransferSize) {
    this.phonehomeMaximumTransferSize = phonehomeMaximumTransferSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalProperties globalProperties = (GlobalProperties) o;
    return Objects.equals(this.disableUsernamePassword, globalProperties.disableUsernamePassword) &&
        Objects.equals(this.phonehomeUploadCadence, globalProperties.phonehomeUploadCadence) &&
        Objects.equals(this.phonehomeMaximumTransferSize, globalProperties.phonehomeMaximumTransferSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disableUsernamePassword, phonehomeUploadCadence, phonehomeMaximumTransferSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalProperties {\n");
    sb.append("    disableUsernamePassword: ").append(toIndentedString(disableUsernamePassword)).append("\n");
    sb.append("    phonehomeUploadCadence: ").append(toIndentedString(phonehomeUploadCadence)).append("\n");
    sb.append("    phonehomeMaximumTransferSize: ").append(toIndentedString(phonehomeMaximumTransferSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

