/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The updatable properties of a Hyperscale Dataset.
 */
@ApiModel(description = "The updatable properties of a Hyperscale Dataset.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class HyperscaleDatasetUpdateParameters {
  public static final String SERIALIZED_NAME_MOUNT_POINT_ID = "mount_point_id";
  @SerializedName(SERIALIZED_NAME_MOUNT_POINT_ID)
  private String mountPointId;

  public static final String SERIALIZED_NAME_CONNECTOR_ID = "connector_id";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_ID)
  private String connectorId;


  public HyperscaleDatasetUpdateParameters mountPointId(String mountPointId) {
    
    this.mountPointId = mountPointId;
    return this;
  }

   /**
   * The Id of the Hyperscale Mount Point used for this Dataset.
   * @return mountPointId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Id of the Hyperscale Mount Point used for this Dataset.")

  public String getMountPointId() {
    return mountPointId;
  }


  public void setMountPointId(String mountPointId) {
    this.mountPointId = mountPointId;
  }


  public HyperscaleDatasetUpdateParameters connectorId(String connectorId) {
    
    this.connectorId = connectorId;
    return this;
  }

   /**
   * Id the Hyperscale Connector used to read sensitive data and write masked data.
   * @return connectorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id the Hyperscale Connector used to read sensitive data and write masked data.")

  public String getConnectorId() {
    return connectorId;
  }


  public void setConnectorId(String connectorId) {
    this.connectorId = connectorId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HyperscaleDatasetUpdateParameters hyperscaleDatasetUpdateParameters = (HyperscaleDatasetUpdateParameters) o;
    return Objects.equals(this.mountPointId, hyperscaleDatasetUpdateParameters.mountPointId) &&
        Objects.equals(this.connectorId, hyperscaleDatasetUpdateParameters.connectorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mountPointId, connectorId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HyperscaleDatasetUpdateParameters {\n");
    sb.append("    mountPointId: ").append(toIndentedString(mountPointId)).append("\n");
    sb.append("    connectorId: ").append(toIndentedString(connectorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

