/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HyperscaleColumnOrField
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class HyperscaleColumnOrField {
  public static final String SERIALIZED_NAME_FIELD_NAME = "field_name";
  @SerializedName(SERIALIZED_NAME_FIELD_NAME)
  private String fieldName;

  public static final String SERIALIZED_NAME_DOMAIN_NAME = "domain_name";
  @SerializedName(SERIALIZED_NAME_DOMAIN_NAME)
  private String domainName;

  public static final String SERIALIZED_NAME_ALGORITHM_NAME = "algorithm_name";
  @SerializedName(SERIALIZED_NAME_ALGORITHM_NAME)
  private String algorithmName;

  public static final String SERIALIZED_NAME_DATE_FORMAT = "date_format";
  @SerializedName(SERIALIZED_NAME_DATE_FORMAT)
  private String dateFormat;

  public static final String SERIALIZED_NAME_ALGORITHM_FIELD_NAME = "algorithm_field_name";
  @SerializedName(SERIALIZED_NAME_ALGORITHM_FIELD_NAME)
  private String algorithmFieldName;

  public static final String SERIALIZED_NAME_ALGORITHM_GROUP_NO = "algorithm_group_no";
  @SerializedName(SERIALIZED_NAME_ALGORITHM_GROUP_NO)
  private Long algorithmGroupNo;


  public HyperscaleColumnOrField fieldName(String fieldName) {
    
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Name of the field.
   * @return fieldName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the field.")

  public String getFieldName() {
    return fieldName;
  }


  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }


  public HyperscaleColumnOrField domainName(String domainName) {
    
    this.domainName = domainName;
    return this;
  }

   /**
   * The name of the domain assigned to this field.
   * @return domainName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the domain assigned to this field.")

  public String getDomainName() {
    return domainName;
  }


  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }


  public HyperscaleColumnOrField algorithmName(String algorithmName) {
    
    this.algorithmName = algorithmName;
    return this;
  }

   /**
   * The name of the algorithm assigned to this field.
   * @return algorithmName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the algorithm assigned to this field.")

  public String getAlgorithmName() {
    return algorithmName;
  }


  public void setAlgorithmName(String algorithmName) {
    this.algorithmName = algorithmName;
  }


  public HyperscaleColumnOrField dateFormat(String dateFormat) {
    
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * The format of the date assigned to this field.
   * @return dateFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The format of the date assigned to this field.")

  public String getDateFormat() {
    return dateFormat;
  }


  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }


  public HyperscaleColumnOrField algorithmFieldName(String algorithmFieldName) {
    
    this.algorithmFieldName = algorithmFieldName;
    return this;
  }

   /**
   * The name of the algorithm field that is associated with this algorithm.
   * @return algorithmFieldName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the algorithm field that is associated with this algorithm.")

  public String getAlgorithmFieldName() {
    return algorithmFieldName;
  }


  public void setAlgorithmFieldName(String algorithmFieldName) {
    this.algorithmFieldName = algorithmFieldName;
  }


  public HyperscaleColumnOrField algorithmGroupNo(Long algorithmGroupNo) {
    
    this.algorithmGroupNo = algorithmGroupNo;
    return this;
  }

   /**
   * The group number of the algorithm to identify a set of columns associated with one instance of algorithm.
   * @return algorithmGroupNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The group number of the algorithm to identify a set of columns associated with one instance of algorithm.")

  public Long getAlgorithmGroupNo() {
    return algorithmGroupNo;
  }


  public void setAlgorithmGroupNo(Long algorithmGroupNo) {
    this.algorithmGroupNo = algorithmGroupNo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HyperscaleColumnOrField hyperscaleColumnOrField = (HyperscaleColumnOrField) o;
    return Objects.equals(this.fieldName, hyperscaleColumnOrField.fieldName) &&
        Objects.equals(this.domainName, hyperscaleColumnOrField.domainName) &&
        Objects.equals(this.algorithmName, hyperscaleColumnOrField.algorithmName) &&
        Objects.equals(this.dateFormat, hyperscaleColumnOrField.dateFormat) &&
        Objects.equals(this.algorithmFieldName, hyperscaleColumnOrField.algorithmFieldName) &&
        Objects.equals(this.algorithmGroupNo, hyperscaleColumnOrField.algorithmGroupNo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, domainName, algorithmName, dateFormat, algorithmFieldName, algorithmGroupNo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HyperscaleColumnOrField {\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    algorithmName: ").append(toIndentedString(algorithmName)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    algorithmFieldName: ").append(toIndentedString(algorithmFieldName)).append("\n");
    sb.append("    algorithmGroupNo: ").append(toIndentedString(algorithmGroupNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

