/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * An uploaded file.
 */
@ApiModel(description = "An uploaded file.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class MaskingFileUpload {
  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @SerializedName(SERIALIZED_NAME_FILENAME)
  private String filename;

  public static final String SERIALIZED_NAME_FILE_REFERENCE_ID = "file_reference_id";
  @SerializedName(SERIALIZED_NAME_FILE_REFERENCE_ID)
  private String fileReferenceId;

  public static final String SERIALIZED_NAME_FILE_SIZE = "file_size";
  @SerializedName(SERIALIZED_NAME_FILE_SIZE)
  private Long fileSize;


  public MaskingFileUpload filename(String filename) {
    
    this.filename = filename;
    return this;
  }

   /**
   * Name of this file.
   * @return filename
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of this file.")

  public String getFilename() {
    return filename;
  }


  public void setFilename(String filename) {
    this.filename = filename;
  }


  public MaskingFileUpload fileReferenceId(String fileReferenceId) {
    
    this.fileReferenceId = fileReferenceId;
    return this;
  }

   /**
   * An reference to this file.
   * @return fileReferenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An reference to this file.")

  public String getFileReferenceId() {
    return fileReferenceId;
  }


  public void setFileReferenceId(String fileReferenceId) {
    this.fileReferenceId = fileReferenceId;
  }


  public MaskingFileUpload fileSize(Long fileSize) {
    
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Size of this file in bytes.
   * @return fileSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Size of this file in bytes.")

  public Long getFileSize() {
    return fileSize;
  }


  public void setFileSize(Long fileSize) {
    this.fileSize = fileSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaskingFileUpload maskingFileUpload = (MaskingFileUpload) o;
    return Objects.equals(this.filename, maskingFileUpload.filename) &&
        Objects.equals(this.fileReferenceId, maskingFileUpload.fileReferenceId) &&
        Objects.equals(this.fileSize, maskingFileUpload.fileSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filename, fileReferenceId, fileSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaskingFileUpload {\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    fileReferenceId: ").append(toIndentedString(fileReferenceId)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

