/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.PhoneHomeBundleApiTelemetry;
import com.delphix.dct.models.PhoneHomeBundleProductInfo;
import com.delphix.dct.models.PhoneHomeBundleRegisteredEngine;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * A bundle containing product identification, configuration information and API telemetry records.
 */
@ApiModel(description = "A bundle containing product identification, configuration information and API telemetry records.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class PhoneHomeBundle {
  public static final String SERIALIZED_NAME_PRODUCT_INFO = "product_info";
  @SerializedName(SERIALIZED_NAME_PRODUCT_INFO)
  private PhoneHomeBundleProductInfo productInfo;

  public static final String SERIALIZED_NAME_REGISTERED_ENGINES = "registered_engines";
  @SerializedName(SERIALIZED_NAME_REGISTERED_ENGINES)
  private List<PhoneHomeBundleRegisteredEngine> registeredEngines = new ArrayList<PhoneHomeBundleRegisteredEngine>();

  public static final String SERIALIZED_NAME_API_TELEMETRY = "api_telemetry";
  @SerializedName(SERIALIZED_NAME_API_TELEMETRY)
  private List<PhoneHomeBundleApiTelemetry> apiTelemetry = new ArrayList<PhoneHomeBundleApiTelemetry>();

  public static final String SERIALIZED_NAME_DATES = "dates";
  @SerializedName(SERIALIZED_NAME_DATES)
  private List<LocalDate> dates = new ArrayList<LocalDate>();

  public static final String SERIALIZED_NAME_BUNDLE_GENERATION_TIME = "bundle_generation_time";
  @SerializedName(SERIALIZED_NAME_BUNDLE_GENERATION_TIME)
  private OffsetDateTime bundleGenerationTime;


  public PhoneHomeBundle productInfo(PhoneHomeBundleProductInfo productInfo) {
    
    this.productInfo = productInfo;
    return this;
  }

   /**
   * Get productInfo
   * @return productInfo
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PhoneHomeBundleProductInfo getProductInfo() {
    return productInfo;
  }


  public void setProductInfo(PhoneHomeBundleProductInfo productInfo) {
    this.productInfo = productInfo;
  }


  public PhoneHomeBundle registeredEngines(List<PhoneHomeBundleRegisteredEngine> registeredEngines) {
    
    this.registeredEngines = registeredEngines;
    return this;
  }

  public PhoneHomeBundle addRegisteredEnginesItem(PhoneHomeBundleRegisteredEngine registeredEnginesItem) {
    this.registeredEngines.add(registeredEnginesItem);
    return this;
  }

   /**
   * A list of Delphix Engines registered with this instance of Data Control Tower.
   * @return registeredEngines
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of Delphix Engines registered with this instance of Data Control Tower.")

  public List<PhoneHomeBundleRegisteredEngine> getRegisteredEngines() {
    return registeredEngines;
  }


  public void setRegisteredEngines(List<PhoneHomeBundleRegisteredEngine> registeredEngines) {
    this.registeredEngines = registeredEngines;
  }


  public PhoneHomeBundle apiTelemetry(List<PhoneHomeBundleApiTelemetry> apiTelemetry) {
    
    this.apiTelemetry = apiTelemetry;
    return this;
  }

  public PhoneHomeBundle addApiTelemetryItem(PhoneHomeBundleApiTelemetry apiTelemetryItem) {
    this.apiTelemetry.add(apiTelemetryItem);
    return this;
  }

   /**
   * A list of API telemetry records.\&quot;
   * @return apiTelemetry
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of API telemetry records.\"")

  public List<PhoneHomeBundleApiTelemetry> getApiTelemetry() {
    return apiTelemetry;
  }


  public void setApiTelemetry(List<PhoneHomeBundleApiTelemetry> apiTelemetry) {
    this.apiTelemetry = apiTelemetry;
  }


  public PhoneHomeBundle dates(List<LocalDate> dates) {
    
    this.dates = dates;
    return this;
  }

  public PhoneHomeBundle addDatesItem(LocalDate datesItem) {
    this.dates.add(datesItem);
    return this;
  }

   /**
   * A list of dates for which telemetry data is included in this bundle.
   * @return dates
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of dates for which telemetry data is included in this bundle.")

  public List<LocalDate> getDates() {
    return dates;
  }


  public void setDates(List<LocalDate> dates) {
    this.dates = dates;
  }


  public PhoneHomeBundle bundleGenerationTime(OffsetDateTime bundleGenerationTime) {
    
    this.bundleGenerationTime = bundleGenerationTime;
    return this;
  }

   /**
   * The UTC time at bundle generation (ISO 8601 format).
   * @return bundleGenerationTime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The UTC time at bundle generation (ISO 8601 format).")

  public OffsetDateTime getBundleGenerationTime() {
    return bundleGenerationTime;
  }


  public void setBundleGenerationTime(OffsetDateTime bundleGenerationTime) {
    this.bundleGenerationTime = bundleGenerationTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneHomeBundle phoneHomeBundle = (PhoneHomeBundle) o;
    return Objects.equals(this.productInfo, phoneHomeBundle.productInfo) &&
        Objects.equals(this.registeredEngines, phoneHomeBundle.registeredEngines) &&
        Objects.equals(this.apiTelemetry, phoneHomeBundle.apiTelemetry) &&
        Objects.equals(this.dates, phoneHomeBundle.dates) &&
        Objects.equals(this.bundleGenerationTime, phoneHomeBundle.bundleGenerationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productInfo, registeredEngines, apiTelemetry, dates, bundleGenerationTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneHomeBundle {\n");
    sb.append("    productInfo: ").append(toIndentedString(productInfo)).append("\n");
    sb.append("    registeredEngines: ").append(toIndentedString(registeredEngines)).append("\n");
    sb.append("    apiTelemetry: ").append(toIndentedString(apiTelemetry)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    bundleGenerationTime: ").append(toIndentedString(bundleGenerationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

