/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.delphix.dct.models.PhoneHomeBundleProductHistory;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Information to identify this Data Control Tower instance.
 */
@ApiModel(description = "Information to identify this Data Control Tower instance.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class PhoneHomeBundleProductInfo {
  public static final String SERIALIZED_NAME_SYSTEM_UUID = "system_uuid";
  @SerializedName(SERIALIZED_NAME_SYSTEM_UUID)
  private String systemUuid;

  public static final String SERIALIZED_NAME_PRODUCT_VERSION = "product_version";
  @SerializedName(SERIALIZED_NAME_PRODUCT_VERSION)
  private String productVersion;

  public static final String SERIALIZED_NAME_API_VERSION = "api_version";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_PRODUCT_UPGRADE_HISTORY = "product_upgrade_history";
  @SerializedName(SERIALIZED_NAME_PRODUCT_UPGRADE_HISTORY)
  private List<PhoneHomeBundleProductHistory> productUpgradeHistory = new ArrayList<PhoneHomeBundleProductHistory>();


  public PhoneHomeBundleProductInfo systemUuid(String systemUuid) {
    
    this.systemUuid = systemUuid;
    return this;
  }

   /**
   * A unique identifier for this Data Control Tower instance.
   * @return systemUuid
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "c67a008d-68fe-2bac-61ec-651c0720f8b1", required = true, value = "A unique identifier for this Data Control Tower instance.")

  public String getSystemUuid() {
    return systemUuid;
  }


  public void setSystemUuid(String systemUuid) {
    this.systemUuid = systemUuid;
  }


  public PhoneHomeBundleProductInfo productVersion(String productVersion) {
    
    this.productVersion = productVersion;
    return this;
  }

   /**
   * The currently running version of this instance of Data Control Tower.
   * @return productVersion
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "15.0.0", required = true, value = "The currently running version of this instance of Data Control Tower.")

  public String getProductVersion() {
    return productVersion;
  }


  public void setProductVersion(String productVersion) {
    this.productVersion = productVersion;
  }


  public PhoneHomeBundleProductInfo apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * The API version in use for this instance of Data Control Tower.
   * @return apiVersion
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3.9.0", required = true, value = "The API version in use for this instance of Data Control Tower.")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public PhoneHomeBundleProductInfo productUpgradeHistory(List<PhoneHomeBundleProductHistory> productUpgradeHistory) {
    
    this.productUpgradeHistory = productUpgradeHistory;
    return this;
  }

  public PhoneHomeBundleProductInfo addProductUpgradeHistoryItem(PhoneHomeBundleProductHistory productUpgradeHistoryItem) {
    this.productUpgradeHistory.add(productUpgradeHistoryItem);
    return this;
  }

   /**
   * The upgrade history of this instance of Data Control Tower.
   * @return productUpgradeHistory
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The upgrade history of this instance of Data Control Tower.")

  public List<PhoneHomeBundleProductHistory> getProductUpgradeHistory() {
    return productUpgradeHistory;
  }


  public void setProductUpgradeHistory(List<PhoneHomeBundleProductHistory> productUpgradeHistory) {
    this.productUpgradeHistory = productUpgradeHistory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneHomeBundleProductInfo phoneHomeBundleProductInfo = (PhoneHomeBundleProductInfo) o;
    return Objects.equals(this.systemUuid, phoneHomeBundleProductInfo.systemUuid) &&
        Objects.equals(this.productVersion, phoneHomeBundleProductInfo.productVersion) &&
        Objects.equals(this.apiVersion, phoneHomeBundleProductInfo.apiVersion) &&
        Objects.equals(this.productUpgradeHistory, phoneHomeBundleProductInfo.productUpgradeHistory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemUuid, productVersion, apiVersion, productUpgradeHistory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneHomeBundleProductInfo {\n");
    sb.append("    systemUuid: ").append(toIndentedString(systemUuid)).append("\n");
    sb.append("    productVersion: ").append(toIndentedString(productVersion)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    productUpgradeHistory: ").append(toIndentedString(productUpgradeHistory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

