/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Web proxy configuration that is used to communicate with Delphix Corp. for support, troubleshooting, upgrades, updates, and patches.
 */
@ApiModel(description = "Web proxy configuration that is used to communicate with Delphix Corp. for support, troubleshooting, upgrades, updates, and patches.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class ProxyConfiguration {
  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_TRUSTSTORE_FILENAME = "truststore_filename";
  @SerializedName(SERIALIZED_NAME_TRUSTSTORE_FILENAME)
  private String truststoreFilename;

  public static final String SERIALIZED_NAME_TRUSTSTORE_PASSWORD = "truststore_password";
  @SerializedName(SERIALIZED_NAME_TRUSTSTORE_PASSWORD)
  private String truststorePassword;


  public ProxyConfiguration host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * The host name or IP address of the proxy server.
   * @return host
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "proxy.server.com", required = true, value = "The host name or IP address of the proxy server.")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public ProxyConfiguration port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * The port number of the proxy server.
   * @return port
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3128", required = true, value = "The port number of the proxy server.")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public ProxyConfiguration username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * The username to use when authenticating with the proxy server.
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "proxy-user", value = "The username to use when authenticating with the proxy server.")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  public ProxyConfiguration password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * The password to use when authenticating with the proxy server.
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "proxy-password", value = "The password to use when authenticating with the proxy server.")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public ProxyConfiguration enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * When set, these settings are enabled. True by default.
   * @return enabled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "When set, these settings are enabled. True by default.")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public ProxyConfiguration truststoreFilename(String truststoreFilename) {
    
    this.truststoreFilename = truststoreFilename;
    return this;
  }

   /**
   * File name of a truststore which can be used to validate the TLS certificate of the proxy server. The truststore must be available at /etc/config/certs/&lt;truststore_filename&gt;
   * @return truststoreFilename
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "File name of a truststore which can be used to validate the TLS certificate of the proxy server. The truststore must be available at /etc/config/certs/<truststore_filename>")

  public String getTruststoreFilename() {
    return truststoreFilename;
  }


  public void setTruststoreFilename(String truststoreFilename) {
    this.truststoreFilename = truststoreFilename;
  }


  public ProxyConfiguration truststorePassword(String truststorePassword) {
    
    this.truststorePassword = truststorePassword;
    return this;
  }

   /**
   * Password for reading trustStore file provided in &#39;truststore_filename&#39; property
   * @return truststorePassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Password for reading trustStore file provided in 'truststore_filename' property")

  public String getTruststorePassword() {
    return truststorePassword;
  }


  public void setTruststorePassword(String truststorePassword) {
    this.truststorePassword = truststorePassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyConfiguration proxyConfiguration = (ProxyConfiguration) o;
    return Objects.equals(this.host, proxyConfiguration.host) &&
        Objects.equals(this.port, proxyConfiguration.port) &&
        Objects.equals(this.username, proxyConfiguration.username) &&
        Objects.equals(this.password, proxyConfiguration.password) &&
        Objects.equals(this.enabled, proxyConfiguration.enabled) &&
        Objects.equals(this.truststoreFilename, proxyConfiguration.truststoreFilename) &&
        Objects.equals(this.truststorePassword, proxyConfiguration.truststorePassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, port, username, password, enabled, truststoreFilename, truststorePassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyConfiguration {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    truststoreFilename: ").append(toIndentedString(truststoreFilename)).append("\n");
    sb.append("    truststorePassword: ").append(toIndentedString(truststorePassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

