/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Parameters to update a masking algorithm revision.
 */
@ApiModel(description = "Parameters to update a masking algorithm revision.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class UpdateAlgorithmRevisionParameters {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;


  public UpdateAlgorithmRevisionParameters name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this algorithm revision.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Address", value = "The name of this algorithm revision.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UpdateAlgorithmRevisionParameters note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * A note of this algorithm revision.
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A note of this algorithm revision.")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAlgorithmRevisionParameters updateAlgorithmRevisionParameters = (UpdateAlgorithmRevisionParameters) o;
    return Objects.equals(this.name, updateAlgorithmRevisionParameters.name) &&
        Objects.equals(this.note, updateAlgorithmRevisionParameters.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, note);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAlgorithmRevisionParameters {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

