/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.9.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Parameters to update a MaskingJob.
 */
@ApiModel(description = "Parameters to update a MaskingJob.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:50:51.668272+05:30[Asia/Kolkata]")
public class UpdateMaskingJobParameters {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CONNECTOR_USERNAME = "connector_username";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_USERNAME)
  private String connectorUsername;

  public static final String SERIALIZED_NAME_CONNECTOR_PASSWORD = "connector_password";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_PASSWORD)
  private String connectorPassword;

  public static final String SERIALIZED_NAME_ON_THE_FLY_SOURCE_CONNECTOR_USERNAME = "on_the_fly_source_connector_username";
  @SerializedName(SERIALIZED_NAME_ON_THE_FLY_SOURCE_CONNECTOR_USERNAME)
  private String onTheFlySourceConnectorUsername;

  public static final String SERIALIZED_NAME_ON_THE_FLY_SOURCE_CONNECTOR_PASSWORD = "on_the_fly_source_connector_password";
  @SerializedName(SERIALIZED_NAME_ON_THE_FLY_SOURCE_CONNECTOR_PASSWORD)
  private String onTheFlySourceConnectorPassword;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DATASET_ID = "dataset_id";
  @SerializedName(SERIALIZED_NAME_DATASET_ID)
  private String datasetId;

  /**
   * Defines whether execution data will be stored after execution is complete (Hyperscale Job only).
   */
  @JsonAdapter(RetainExecutionDataEnum.Adapter.class)
  public enum RetainExecutionDataEnum {
    NO("NO"),
    
    ON_ERROR("ON_ERROR"),
    
    ALWAYS("ALWAYS");

    private String value;

    RetainExecutionDataEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RetainExecutionDataEnum fromValue(String value) {
      for (RetainExecutionDataEnum b : RetainExecutionDataEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RetainExecutionDataEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RetainExecutionDataEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RetainExecutionDataEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RetainExecutionDataEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RETAIN_EXECUTION_DATA = "retain_execution_data";
  @SerializedName(SERIALIZED_NAME_RETAIN_EXECUTION_DATA)
  private RetainExecutionDataEnum retainExecutionData;

  public static final String SERIALIZED_NAME_MAX_MEMORY = "max_memory";
  @SerializedName(SERIALIZED_NAME_MAX_MEMORY)
  private Integer maxMemory;

  public static final String SERIALIZED_NAME_MIN_MEMORY = "min_memory";
  @SerializedName(SERIALIZED_NAME_MIN_MEMORY)
  private Integer minMemory;

  public static final String SERIALIZED_NAME_FEEDBACK_SIZE = "feedback_size";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_SIZE)
  private Integer feedbackSize;

  public static final String SERIALIZED_NAME_STREAM_ROW_LIMIT = "stream_row_limit";
  @SerializedName(SERIALIZED_NAME_STREAM_ROW_LIMIT)
  private Integer streamRowLimit;

  public static final String SERIALIZED_NAME_NUM_INPUT_STREAMS = "num_input_streams";
  @SerializedName(SERIALIZED_NAME_NUM_INPUT_STREAMS)
  private Integer numInputStreams;

  public static final String SERIALIZED_NAME_MAX_CONCURRENT_SOURCE_CONNECTIONS = "max_concurrent_source_connections";
  @SerializedName(SERIALIZED_NAME_MAX_CONCURRENT_SOURCE_CONNECTIONS)
  private Integer maxConcurrentSourceConnections;

  public static final String SERIALIZED_NAME_MAX_CONCURRENT_TARGET_CONNECTIONS = "max_concurrent_target_connections";
  @SerializedName(SERIALIZED_NAME_MAX_CONCURRENT_TARGET_CONNECTIONS)
  private Integer maxConcurrentTargetConnections;

  public static final String SERIALIZED_NAME_PARALLELISM_DEGREE = "parallelism_degree";
  @SerializedName(SERIALIZED_NAME_PARALLELISM_DEGREE)
  private Integer parallelismDegree;


  public UpdateMaskingJobParameters name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the MaskingJob.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My favorite MaskingJob", value = "The name of the MaskingJob.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UpdateMaskingJobParameters connectorUsername(String connectorUsername) {
    
    this.connectorUsername = connectorUsername;
    return this;
  }

   /**
   * The username of the Connector used by the MaskingJob. (Standard Job only).
   * @return connectorUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "user123", value = "The username of the Connector used by the MaskingJob. (Standard Job only).")

  public String getConnectorUsername() {
    return connectorUsername;
  }


  public void setConnectorUsername(String connectorUsername) {
    this.connectorUsername = connectorUsername;
  }


  public UpdateMaskingJobParameters connectorPassword(String connectorPassword) {
    
    this.connectorPassword = connectorPassword;
    return this;
  }

   /**
   * The password of the Connector used by the MaskingJob. (Standard Job only).
   * @return connectorPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "password123", value = "The password of the Connector used by the MaskingJob. (Standard Job only).")

  public String getConnectorPassword() {
    return connectorPassword;
  }


  public void setConnectorPassword(String connectorPassword) {
    this.connectorPassword = connectorPassword;
  }


  public UpdateMaskingJobParameters onTheFlySourceConnectorUsername(String onTheFlySourceConnectorUsername) {
    
    this.onTheFlySourceConnectorUsername = onTheFlySourceConnectorUsername;
    return this;
  }

   /**
   * The username of the source Connector used by the on-the-fly MaskingJob. (Standard Job only).
   * @return onTheFlySourceConnectorUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "user123", value = "The username of the source Connector used by the on-the-fly MaskingJob. (Standard Job only).")

  public String getOnTheFlySourceConnectorUsername() {
    return onTheFlySourceConnectorUsername;
  }


  public void setOnTheFlySourceConnectorUsername(String onTheFlySourceConnectorUsername) {
    this.onTheFlySourceConnectorUsername = onTheFlySourceConnectorUsername;
  }


  public UpdateMaskingJobParameters onTheFlySourceConnectorPassword(String onTheFlySourceConnectorPassword) {
    
    this.onTheFlySourceConnectorPassword = onTheFlySourceConnectorPassword;
    return this;
  }

   /**
   * The password of the source Connector used by the on-the-fly MaskingJob. (Standard Job only).
   * @return onTheFlySourceConnectorPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "password123", value = "The password of the source Connector used by the on-the-fly MaskingJob. (Standard Job only).")

  public String getOnTheFlySourceConnectorPassword() {
    return onTheFlySourceConnectorPassword;
  }


  public void setOnTheFlySourceConnectorPassword(String onTheFlySourceConnectorPassword) {
    this.onTheFlySourceConnectorPassword = onTheFlySourceConnectorPassword;
  }


  public UpdateMaskingJobParameters description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the Job (Hyperscale Job only).
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Job for app finance", value = "Description of the Job (Hyperscale Job only).")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public UpdateMaskingJobParameters datasetId(String datasetId) {
    
    this.datasetId = datasetId;
    return this;
  }

   /**
   * Dataset of the Hyperscale Job (Hyperscale Job only).
   * @return datasetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "dataset-123", value = "Dataset of the Hyperscale Job (Hyperscale Job only).")

  public String getDatasetId() {
    return datasetId;
  }


  public void setDatasetId(String datasetId) {
    this.datasetId = datasetId;
  }


  public UpdateMaskingJobParameters retainExecutionData(RetainExecutionDataEnum retainExecutionData) {
    
    this.retainExecutionData = retainExecutionData;
    return this;
  }

   /**
   * Defines whether execution data will be stored after execution is complete (Hyperscale Job only).
   * @return retainExecutionData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Defines whether execution data will be stored after execution is complete (Hyperscale Job only).")

  public RetainExecutionDataEnum getRetainExecutionData() {
    return retainExecutionData;
  }


  public void setRetainExecutionData(RetainExecutionDataEnum retainExecutionData) {
    this.retainExecutionData = retainExecutionData;
  }


  public UpdateMaskingJobParameters maxMemory(Integer maxMemory) {
    
    this.maxMemory = maxMemory;
    return this;
  }

   /**
   * Maximum memory to be allocated for each Masking job (Hyperscale Job only).
   * @return maxMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1024", value = "Maximum memory to be allocated for each Masking job (Hyperscale Job only).")

  public Integer getMaxMemory() {
    return maxMemory;
  }


  public void setMaxMemory(Integer maxMemory) {
    this.maxMemory = maxMemory;
  }


  public UpdateMaskingJobParameters minMemory(Integer minMemory) {
    
    this.minMemory = minMemory;
    return this;
  }

   /**
   * Minimum memory to be allocated for each Masking job (Hyperscale Job only).
   * @return minMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1024", value = "Minimum memory to be allocated for each Masking job (Hyperscale Job only).")

  public Integer getMinMemory() {
    return minMemory;
  }


  public void setMinMemory(Integer minMemory) {
    this.minMemory = minMemory;
  }


  public UpdateMaskingJobParameters feedbackSize(Integer feedbackSize) {
    
    this.feedbackSize = feedbackSize;
    return this;
  }

   /**
   * Feedback Size for each Masking job (Hyperscale Job only).
   * @return feedbackSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "32", value = "Feedback Size for each Masking job (Hyperscale Job only).")

  public Integer getFeedbackSize() {
    return feedbackSize;
  }


  public void setFeedbackSize(Integer feedbackSize) {
    this.feedbackSize = feedbackSize;
  }


  public UpdateMaskingJobParameters streamRowLimit(Integer streamRowLimit) {
    
    this.streamRowLimit = streamRowLimit;
    return this;
  }

   /**
   * Stream Row Limit for each Masking job (Hyperscale Job only).
   * @return streamRowLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "Stream Row Limit for each Masking job (Hyperscale Job only).")

  public Integer getStreamRowLimit() {
    return streamRowLimit;
  }


  public void setStreamRowLimit(Integer streamRowLimit) {
    this.streamRowLimit = streamRowLimit;
  }


  public UpdateMaskingJobParameters numInputStreams(Integer numInputStreams) {
    
    this.numInputStreams = numInputStreams;
    return this;
  }

   /**
   * Number of input streams to be configured for Masking Job (Hyperscale Job only).
   * @return numInputStreams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "Number of input streams to be configured for Masking Job (Hyperscale Job only).")

  public Integer getNumInputStreams() {
    return numInputStreams;
  }


  public void setNumInputStreams(Integer numInputStreams) {
    this.numInputStreams = numInputStreams;
  }


  public UpdateMaskingJobParameters maxConcurrentSourceConnections(Integer maxConcurrentSourceConnections) {
    
    this.maxConcurrentSourceConnections = maxConcurrentSourceConnections;
    return this;
  }

   /**
   * Maximum number of parallel connection that the Hyperscale instance can have with the source datasource (Hyperscale Job only).
   * @return maxConcurrentSourceConnections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "32", value = "Maximum number of parallel connection that the Hyperscale instance can have with the source datasource (Hyperscale Job only).")

  public Integer getMaxConcurrentSourceConnections() {
    return maxConcurrentSourceConnections;
  }


  public void setMaxConcurrentSourceConnections(Integer maxConcurrentSourceConnections) {
    this.maxConcurrentSourceConnections = maxConcurrentSourceConnections;
  }


  public UpdateMaskingJobParameters maxConcurrentTargetConnections(Integer maxConcurrentTargetConnections) {
    
    this.maxConcurrentTargetConnections = maxConcurrentTargetConnections;
    return this;
  }

   /**
   * Maximum number of parallel connection that the Hyperscale instance can have with the target datasource (Hyperscale Job only).
   * @return maxConcurrentTargetConnections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "32", value = "Maximum number of parallel connection that the Hyperscale instance can have with the target datasource (Hyperscale Job only).")

  public Integer getMaxConcurrentTargetConnections() {
    return maxConcurrentTargetConnections;
  }


  public void setMaxConcurrentTargetConnections(Integer maxConcurrentTargetConnections) {
    this.maxConcurrentTargetConnections = maxConcurrentTargetConnections;
  }


  public UpdateMaskingJobParameters parallelismDegree(Integer parallelismDegree) {
    
    this.parallelismDegree = parallelismDegree;
    return this;
  }

   /**
   * The degree of parallelism (DOP) per Oracle job to recreate the index in the post-load process (Hyperscale Job only).
   * @return parallelismDegree
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "The degree of parallelism (DOP) per Oracle job to recreate the index in the post-load process (Hyperscale Job only).")

  public Integer getParallelismDegree() {
    return parallelismDegree;
  }


  public void setParallelismDegree(Integer parallelismDegree) {
    this.parallelismDegree = parallelismDegree;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMaskingJobParameters updateMaskingJobParameters = (UpdateMaskingJobParameters) o;
    return Objects.equals(this.name, updateMaskingJobParameters.name) &&
        Objects.equals(this.connectorUsername, updateMaskingJobParameters.connectorUsername) &&
        Objects.equals(this.connectorPassword, updateMaskingJobParameters.connectorPassword) &&
        Objects.equals(this.onTheFlySourceConnectorUsername, updateMaskingJobParameters.onTheFlySourceConnectorUsername) &&
        Objects.equals(this.onTheFlySourceConnectorPassword, updateMaskingJobParameters.onTheFlySourceConnectorPassword) &&
        Objects.equals(this.description, updateMaskingJobParameters.description) &&
        Objects.equals(this.datasetId, updateMaskingJobParameters.datasetId) &&
        Objects.equals(this.retainExecutionData, updateMaskingJobParameters.retainExecutionData) &&
        Objects.equals(this.maxMemory, updateMaskingJobParameters.maxMemory) &&
        Objects.equals(this.minMemory, updateMaskingJobParameters.minMemory) &&
        Objects.equals(this.feedbackSize, updateMaskingJobParameters.feedbackSize) &&
        Objects.equals(this.streamRowLimit, updateMaskingJobParameters.streamRowLimit) &&
        Objects.equals(this.numInputStreams, updateMaskingJobParameters.numInputStreams) &&
        Objects.equals(this.maxConcurrentSourceConnections, updateMaskingJobParameters.maxConcurrentSourceConnections) &&
        Objects.equals(this.maxConcurrentTargetConnections, updateMaskingJobParameters.maxConcurrentTargetConnections) &&
        Objects.equals(this.parallelismDegree, updateMaskingJobParameters.parallelismDegree);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, connectorUsername, connectorPassword, onTheFlySourceConnectorUsername, onTheFlySourceConnectorPassword, description, datasetId, retainExecutionData, maxMemory, minMemory, feedbackSize, streamRowLimit, numInputStreams, maxConcurrentSourceConnections, maxConcurrentTargetConnections, parallelismDegree);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMaskingJobParameters {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    connectorUsername: ").append(toIndentedString(connectorUsername)).append("\n");
    sb.append("    connectorPassword: ").append(toIndentedString(connectorPassword)).append("\n");
    sb.append("    onTheFlySourceConnectorUsername: ").append(toIndentedString(onTheFlySourceConnectorUsername)).append("\n");
    sb.append("    onTheFlySourceConnectorPassword: ").append(toIndentedString(onTheFlySourceConnectorPassword)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    retainExecutionData: ").append(toIndentedString(retainExecutionData)).append("\n");
    sb.append("    maxMemory: ").append(toIndentedString(maxMemory)).append("\n");
    sb.append("    minMemory: ").append(toIndentedString(minMemory)).append("\n");
    sb.append("    feedbackSize: ").append(toIndentedString(feedbackSize)).append("\n");
    sb.append("    streamRowLimit: ").append(toIndentedString(streamRowLimit)).append("\n");
    sb.append("    numInputStreams: ").append(toIndentedString(numInputStreams)).append("\n");
    sb.append("    maxConcurrentSourceConnections: ").append(toIndentedString(maxConcurrentSourceConnections)).append("\n");
    sb.append("    maxConcurrentTargetConnections: ").append(toIndentedString(maxConcurrentTargetConnections)).append("\n");
    sb.append("    parallelismDegree: ").append(toIndentedString(parallelismDegree)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

